### ISSUE TITLE
Aerostack2 v1.1 release

### ISSUE THREAD

**Issue by pariaspe** [aerostack2/aerostack2#530]
## Pending

- [x] #388
- [x] #488
- [x] #490
- [x] #499
- [x] #501
- [x] #511
- [x] #527
- [x] #528
- [x] #529
- [x] https://github.com/aerostack2/as2_platform_crazyflie/issues/1
- [x] ~~https://github.com/aerostack2/as2_platform_dji_osdk/issues/4~~
- [ ] https://github.com/aerostack2/as2_platform_pixhawk/issues/19
- [x] ~~#531~~
- [x] #534 

## Ready to go
- [x] ROS2 Galactic EOL (#456)
- [x] Support for Gazebo Harmonic (#454)
- [x] New platform **as2_platform_dji_psdk** (#462)
- [x] New platform **as2_multirotor_simulator** (#463)
- [x] **as2_sensors** reformat (see #461)
- [x] Platforms with third-parties dependencies moved out from main repository (#465)
- [x] Continuous Integration tests included platforms outside main repository (#472, #524)
- [x] Continuous Deployment on docker (nightly and humble) (#457)
- [x] Mocap plugin at **as2_state_estimator** now uses MOCAP4ROS2 project (#349)
- [x] New gimbal sensor at **as2_gazebo_assets** (#429, #466)
- [x] General documentation improvements (added tello, migration guide to Gz Harmonic...)

**Comment by pariaspe** [comment]
Aerostack2 packages from main repository released! Platforms still pending
